"""Extract a bounded, offline overview label set from Natural Earth GeoJSON.

Usage: python scripts/prepare_place_labels.py countries.geojson places.geojson
Source: github.com/nvkelso/natural-earth-vector/geojson (public domain).
The compact result contains label points only, never political boundaries.
"""
import json
import sys
from pathlib import Path

rows = []
countries, places = [json.loads(Path(p).read_text(encoding="utf-8")) for p in sys.argv[1:3]]
for feature in countries["features"]:
    p = feature["properties"]
    rows.append([p["NAME_EN"], round(p["LABEL_X"], 4), round(p["LABEL_Y"], 4), "country", p["LABELRANK"]])
for feature in places["features"]:
    p = feature["properties"]
    x, y = feature["geometry"]["coordinates"]
    rows.append([p["name"], round(x, 4), round(y, 4), "city", p["scalerank"]])
assert len(rows) < 500
rows.sort(key=lambda r: (r[3], r[4], r[0]))
output = Path(__file__).resolve().parents[1] / "src/data/naturalEarthLabels.js"
output.write_text('// Natural Earth, public domain. Generated by scripts/prepare_place_labels.py.\n'
                  + 'export const NATURAL_EARTH_LABELS = [\n'
                  + ',\n'.join('  ' + json.dumps(r, ensure_ascii=False) for r in rows) + '\n];\n', encoding="utf-8")
print(f"{len(rows)} overview labels")
